name: uboot
on:
  workflow_dispatch:

jobs:
  toolchain:
    name: Uboot
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi gcc-mipsel-linux-gnu u-boot-tools lzop gnutls-dev lzma-alone build-essential

      - name: Sigmastar
        run: |
          git clone https://github.com/augin/u-boot-msc313e --depth 1
          cd u-boot-msc313e
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi- 
          make infinity3_defconfig
          make -j5

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            u-boot-*/output/u-boot-msc316dm-nor.bin
